name: Publish to PyPI

on:
  push:
    tags:
      - 'v*'  # Trigger the workflow on tag push matching 'v*'. Example: v1.0.0

jobs:
  create_release:
    name: Create GitHub Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.x  # Replace 'x' with your desired Python version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install setuptools wheel twine

      - name: Build distribution
        run: python setup.py sdist bdist_wheel

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload tar.gz
        uses: actions/upload-artifact@v3
        with:
          name: Release Files
          path: dist/*.tar.gz

      - name: Upload wheel
        uses: actions/upload-artifact@v3
        with:
          name: Release Files
          path: dist/*.whl