name: Publish to PyPI

on:
  workflow_dispatch:  # Manually triggered workflow

jobs:
  publish:
    name: Publish threadspy to PyPI
    runs-on: ubuntu-latest
    environment:
      name: PyPI Publishing

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.x 

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install setuptools wheel twine

      - name: Build distribution
        run: python setup.py sdist bdist_wheel

      - name: Publish to PyPI
        if: github.ref == 'refs/heads/master'
        env:
          TWINE_USERNAME: "__token__"
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}  # Use the PyPI API token secret
        run: twine upload dist/*
